site_name: Fabric Gateway
site_description: Go, Node and Java client API for Hyperledger Fabric
repo_url: https://github.com/hyperledger/fabric-gateway/
theme:
  name: material
  logo: assets/Hyperledger_Fabric_White.svg
  features:
    - navigation.
extra:
  social:
    - icon: octicons/comment-discussion-16
      link: https://github.com/hyperledger/fabric-gateway/discussions
      name: GitHub discussions
    - icon: fontawesome/brands/discord
      link: https://discord.gg/hyperledger
      name: Hyperledger Discord
    - icon: fontawesome/regular/envelope
      link: https://lists.hyperledger.org/g/fabric
      name: Fabric mailing list
