name: "Security vulnerability scan"

on:
  workflow_call:
    inputs:
      ref:
        description: Branch, tag or SHA to scan.
        type: string
        required: false
        default: ""
      upload-sarif:
        description: Whether to upload to Security > Code Scanning.
        type: boolean
        required: false
        default: false

permissions:
  actions: read
  contents: read
  security-events: write

jobs:
  go-config:
    name: Go scanner config
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5.5.0
        with:
          go-version: stable
          cache: false
          check-latest: true
      - name: Create OSV-Scanner config
        run: |
          echo "GoVersionOverride = '$(go env GOVERSION | sed -e 's/^go//' -e 's/-.*$//')'" > osv-scanner.toml
      - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: go-config
          path: osv-scanner.toml
          if-no-files-found: error

  go:
    needs: go-config
    uses: google/osv-scanner-action/.github/workflows/osv-scanner-reusable.yml@40a8940a65eab1544a6af759e43d936201a131a2 # v2.0.3
    with:
      ref: ${{ inputs.ref }}
      results-file-name: go-results.sarif
      upload-sarif: ${{ inputs.upload-sarif }}
      download-artifact: go-config
      matrix-property: "go-"
      scan-args: |
        --config=osv-scanner.toml
        --lockfile=go.mod

  node-bom:
    name: Node BOM
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          ref: ${{ inputs.ref }}
      - name: Set up Node
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: "lts/*"
      - name: Create BOM
        working-directory: node
        run: |
          npm install --omit=dev --package-lock-only --no-audit
          npm sbom --omit=dev --package-lock-only --sbom-format cyclonedx > ../bom.cdx.json
      - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: node-bom
          path: bom.cdx.json
          if-no-files-found: error

  node:
    needs: node-bom
    uses: google/osv-scanner-action/.github/workflows/osv-scanner-reusable.yml@40a8940a65eab1544a6af759e43d936201a131a2 # v2.0.3
    with:
      ref: ${{ inputs.ref }}
      results-file-name: node-results.sarif
      upload-sarif: ${{ inputs.upload-sarif }}
      download-artifact: node-bom
      matrix-property: "node-"
      scan-args: |
        --sbom=bom.cdx.json

  java:
    uses: google/osv-scanner-action/.github/workflows/osv-scanner-reusable.yml@40a8940a65eab1544a6af759e43d936201a131a2 # v2.0.3
    with:
      ref: ${{ inputs.ref }}
      results-file-name: java-results.sarif
      upload-sarif: ${{ inputs.upload-sarif }}
      matrix-property: "java-"
      scan-args: |
        --lockfile=java/pom.xml
